# Generated by Django 3.0.4 on 2020-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_case', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Corona Virus Data',
            },
        ),
    ]
