# Generated by Django 3.0.4 on 2020-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0002_auto_20200324_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='_', max_length=500)),
                ('total_case', models.IntegerField(default=0)),
                ('new_case', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('new_death', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('serious', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coronadata',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Corona Virus Data'},
        ),
    ]
