# Generated by Django 3.0.4 on 2020-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0003_auto_20200324_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='countrydata',
            options={'ordering': ['-total_case'], 'verbose_name': 'Contry Data'},
        ),
    ]
